# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'YourPlaces' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'GooglePlaces’
pod 'GoogleMaps’
pod 'GooglePlacePicker’
pod 'SDWebImage', '~>4.0'
# pod 'AlamofireObjectMapper', '~> 4.0'
pod 'SwiftyJSON'
pod 'Cosmos', '~> 9.0'
pod 'RealmSwift', '~> 2.7.0'

end
